language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fabien45/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fabien45/react-test npm test

after_success:
  - docker build -t fabien45/multi-client ./client
  - docker build -t fabien45/multi-nginx ./nginx
  - docker build -t fabien45/multi-server ./server
  - docker build -t fabien45/multi-worker ./worker
  # Log in in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push fabien45/multi-client
  - docker push fabien45/multi-nginx
  - docker push fabien45/multi-server
  - docker push fabien45/multi-worker